-- MySQL Script generated by MySQL Workbench
-- 03/30/15 00:09:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concordancedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concordancedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `concordancedb` ;

-- -----------------------------------------------------
-- Table `concordancedb`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  `author` VARCHAR(45) NULL DEFAULT 'Unknown',
  `diff` INT NOT NULL DEFAULT 0,
  `file_name` VARCHAR(45) NULL,
  `full_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `concordancedb`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`words` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(80) NOT NULL,
  `total_num_of_appearance` INT NULL,
  `num_of_recipes_appearance` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concordancedb`.`words_in_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`words_in_recipes` (
  `word_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `word_index_in_recipe` INT NOT NULL,
  `line_index` INT NOT NULL,
  `word_index_in_line` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `word_index_in_recipe`),
  INDEX `wir_word_id_idx` (`word_id` ASC),
  CONSTRAINT `wir_word_id`
    FOREIGN KEY (`word_id`)
    REFERENCES `concordancedb`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wir_recipe_id`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `concordancedb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concordancedb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`groups` (
  `group_id` INT NOT NULL,
  `group_name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(150) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concordancedb`.`words_in_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`words_in_groups` (
  `group_id` INT NOT NULL,
  `word_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `word_id`),
  INDEX `wig_word_id_idx` (`word_id` ASC),
  CONSTRAINT `wig_word_id`
    FOREIGN KEY (`word_id`)
    REFERENCES `concordancedb`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wig_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `concordancedb`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concordancedb`.`couples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`couples` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Comment` VARCHAR(140) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concordancedb`.`words_in_couples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concordancedb`.`words_in_couples` (
  `couple_id` INT NOT NULL,
  `word_id1` INT NOT NULL,
  `word_id2` INT NOT NULL,
  PRIMARY KEY (`couple_id`),
  INDEX `wic_word_id1_idx` (`word_id1` ASC),
  INDEX `wic_word_id2_idx` (`word_id2` ASC),
  CONSTRAINT `wic_couple_id`
    FOREIGN KEY (`couple_id`)
    REFERENCES `concordancedb`.`couples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wic_word_id1`
    FOREIGN KEY (`word_id1`)
    REFERENCES `concordancedb`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wic_word_id2`
    FOREIGN KEY (`word_id2`)
    REFERENCES `concordancedb`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
